/**
 * Offline Cryptographic Software License Verifier
 * 
 * Verifies ECDSA P-256 (SHA-256) digital signatures generated by the developer's offline private key.
 * Uses the WebCrypto (SubtleCrypto) API for 100% offline, zero-dependency cryptographic validation.
 */

// Embedded Developer Public Key (SPKI format)
export const EMBEDDED_PUBLIC_KEY_BASE64 =
  'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzXq3F042JWSHrlnU40P+8IgAVI+A6tQorsArYiBMOUAYoDGvFHE2Tjzmt+SSdXyEVvvlEioQTExyqase/wPzAQ==';

export interface LicensePayload {
  version: number;
  product: string;
  licenseType: 'subscription' | 'lifetime' | 'trial';
  machineId: string;
  clientName: string;
  licensee?: string;
  issuedAt: string;
  expiresAt: string | null;
}

export interface LicenseDocument {
  payload: LicensePayload;
  signature: string; // Base64 DER-encoded ECDSA signature
}

export type LicenseVerificationStatus =
  | 'VALID'
  | 'EXPIRED'
  | 'MACHINE_MISMATCH'
  | 'INVALID_SIGNATURE'
  | 'CORRUPTED_DOCUMENT'
  | 'CLOCK_TAMPER_DETECTED'
  | 'UNLICENSED';

export interface LicenseVerificationResult {
  status: LicenseVerificationStatus;
  isValid: boolean;
  message: string;
  payload?: LicensePayload;
  daysRemaining?: number | null; // null for lifetime
}

/**
 * Converts a base64 string to Uint8Array.
 */
function base64ToUint8Array(base64Str: string): Uint8Array {
  const binaryString = atob(base64Str.trim());
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}

/**
 * Converts ASN.1 DER ECDSA signature (from Node.js crypto / OpenSSL) into IEEE P1363 format (r||s 64-byte buffer)
 * expected by browser SubtleCrypto.
 */
function derToP1363(derBytes: Uint8Array): Uint8Array {
  // If already 64 bytes, it's already P1363
  if (derBytes.length === 64) {
    return derBytes;
  }

  let offset = 0;
  if (derBytes[offset++] !== 0x30) {
    throw new Error('Invalid DER signature header');
  }

  let seqLen = derBytes[offset++];
  if (seqLen & 0x80) {
    const lenBytes = seqLen & 0x7f;
    offset += lenBytes;
  }

  // Parse r
  if (derBytes[offset++] !== 0x02) throw new Error('Invalid DER integer marker for r');
  let rLen = derBytes[offset++];
  let rBytes = derBytes.subarray(offset, offset + rLen);
  offset += rLen;

  // Strip leading 00 padding byte if present
  if (rBytes.length > 32 && rBytes[0] === 0x00) {
    rBytes = rBytes.subarray(1);
  }

  // Parse s
  if (derBytes[offset++] !== 0x02) throw new Error('Invalid DER integer marker for s');
  let sLen = derBytes[offset++];
  let sBytes = derBytes.subarray(offset, offset + sLen);

  // Strip leading 00 padding byte if present
  if (sBytes.length > 32 && sBytes[0] === 0x00) {
    sBytes = sBytes.subarray(1);
  }

  const p1363 = new Uint8Array(64);
  // Copy r right-aligned in 32 bytes
  p1363.set(rBytes, 32 - rBytes.length);
  // Copy s right-aligned in second 32 bytes
  p1363.set(sBytes, 64 - sBytes.length);

  return p1363;
}

/**
 * Imports the embedded ECDSA P-256 Public Key into WebCrypto SubtleCrypto.
 */
let cachedCryptoKey: CryptoKey | null = null;
async function getVerifyKey(): Promise<CryptoKey> {
  if (cachedCryptoKey) return cachedCryptoKey;

  const keyBuffer = base64ToUint8Array(EMBEDDED_PUBLIC_KEY_BASE64);
  cachedCryptoKey = await crypto.subtle.importKey(
    'spki',
    keyBuffer as unknown as BufferSource,
    {
      name: 'ECDSA',
      namedCurve: 'P-256',
    },
    false,
    ['verify']
  );
  return cachedCryptoKey;
}

/**
 * Parses raw license input (which can be a JSON string, .lic file content, or Base64 string).
 */
export function parseLicenseInput(input: string): LicenseDocument | null {
  if (!input || !input.trim()) return null;

  const clean = input.trim();

  // 1. Try directly parsing as JSON
  try {
    const doc = JSON.parse(clean);
    if (doc && doc.payload && doc.signature) {
      return doc as LicenseDocument;
    }
  } catch {
    // Not raw JSON, continue to base64 check
  }

  // 2. Try base64 decoding to JSON
  try {
    const decoded = atob(clean);
    const doc = JSON.parse(decoded);
    if (doc && doc.payload && doc.signature) {
      return doc as LicenseDocument;
    }
  } catch {
    // Not valid base64 JSON
  }

  return null;
}

/**
 * Canonical JSON stringifier (sorts keys alphabetically) matching developer generation script.
 */
function toCanonicalString(payload: any): string {
  return JSON.stringify(payload, Object.keys(payload).sort());
}

/**
 * Cryptographically verifies a license against the current host PC's Machine ID.
 */
export async function verifyLicense(
  licenseDoc: LicenseDocument,
  currentMachineId: string,
  lastKnownTimestamp?: number
): Promise<LicenseVerificationResult> {
  try {
    const { payload, signature } = licenseDoc;

    if (!payload || !signature || !payload.machineId || !payload.clientName || !payload.issuedAt) {
      return {
        status: 'CORRUPTED_DOCUMENT',
        isValid: false,
        message: 'License file format is corrupted or missing mandatory fields.',
      };
    }

    // 1. Cryptographic Digital Signature Verification
    const cryptoKey = await getVerifyKey();
    const canonicalPayload = toCanonicalString(payload);
    const dataBytes = new TextEncoder().encode(canonicalPayload);
    const rawSignatureBytes = base64ToUint8Array(signature);
    const p1363Signature = derToP1363(rawSignatureBytes);

    const isSignatureValid = await crypto.subtle.verify(
      {
        name: 'ECDSA',
        hash: { name: 'SHA-256' },
      },
      cryptoKey,
      p1363Signature as unknown as BufferSource,
      dataBytes as unknown as BufferSource
    );

    if (!isSignatureValid) {
      return {
        status: 'INVALID_SIGNATURE',
        isValid: false,
        message: 'Digital signature verification failed. The license file has been modified, tampered with, or is invalid.',
      };
    }

    // 2. Hardware Machine ID Check (Supports '*' for developer testing)
    const normLicenseMachine = payload.machineId.trim().toUpperCase();
    const normCurrentMachine = currentMachineId.trim().toUpperCase();

    if (normLicenseMachine !== '*' && normLicenseMachine !== normCurrentMachine) {
      return {
        status: 'MACHINE_MISMATCH',
        isValid: false,
        message: `Machine ID mismatch. This license is registered for [${normLicenseMachine}], but this computer is [${normCurrentMachine}].`,
        payload,
      };
    }

    // 3. Anti-Clock Tampering Check
    const now = new Date();
    const issuedDate = new Date(payload.issuedAt);

    if (now.getTime() < issuedDate.getTime() - 24 * 60 * 60 * 1000) {
      return {
        status: 'CLOCK_TAMPER_DETECTED',
        isValid: false,
        message: 'System clock error. Your computer clock is set before the license issue date.',
        payload,
      };
    }

    if (lastKnownTimestamp && now.getTime() < lastKnownTimestamp - 30 * 60 * 1000) {
      return {
        status: 'CLOCK_TAMPER_DETECTED',
        isValid: false,
        message: 'System clock tampering detected. Your computer clock has been wound backwards.',
        payload,
      };
    }

    // 4. Expiration Date Check
    let daysRemaining: number | null = null;
    if (payload.expiresAt) {
      const expDate = new Date(payload.expiresAt);
      const diffMs = expDate.getTime() - now.getTime();
      daysRemaining = Math.max(0, Math.ceil(diffMs / (1000 * 60 * 60 * 24)));

      if (now.getTime() > expDate.getTime()) {
        return {
          status: 'EXPIRED',
          isValid: false,
          message: `License expired on ${payload.expiresAt.slice(0, 10)}. Please renew your software subscription.`,
          payload,
          daysRemaining: 0,
        };
      }
    }

    return {
      status: 'VALID',
      isValid: true,
      message: `License active and verified for ${payload.clientName}.`,
      payload,
      daysRemaining,
    };
  } catch (err: any) {
    console.error('License verification exception:', err);
    return {
      status: 'CORRUPTED_DOCUMENT',
      isValid: false,
      message: `Verification error: ${err?.message || 'Invalid format'}`,
    };
  }
}
